"""Replace sample references in a Cubase-exported track archive.

Never edits CPR bytes. The host imports channel settings onto matching tracks,
with Events/Parts and Automation disabled, preserving the existing MIDI.
"""
from pathlib import Path
import copy
import hashlib
import json
import struct
import zlib
from xml.etree import ElementTree as ET


PATH_MARKER = b"\x04\x00\x00\x003E8\x00\x02\x00\x07\x00"


def unpack_component(text):
    raw = bytes.fromhex("".join(text.split()))
    if len(raw) < 18 or struct.unpack_from("<I", raw, 12)[0] != len(raw)-16:
        raise ValueError("Unsupported Cubase sampler state envelope")
    body = zlib.decompress(raw[16:])
    if b"SamplerTrackDoc\0" not in body or body.count(PATH_MARKER) != 1:
        raise ValueError("Not a supported Sampler Track state")
    return raw[:12], body


def sample_field(body):
    at = body.index(PATH_MARKER) + len(PATH_MARKER)
    length = struct.unpack_from("<I", body, at)[0]
    if length < 2 or length % 2 or at+4+length > len(body):
        raise ValueError("Invalid sampler filename field")
    return at, length, body[at+4:at+4+length].decode("utf-16-le").rstrip("\0")


def replace_component_path(text, path):
    prefix, body = unpack_component(text)
    at, length, _ = sample_field(body)
    encoded = (str(Path(path).resolve()) + "\0").encode("utf-16-le")
    changed = body[:at] + struct.pack("<I", len(encoded)) + encoded + body[at+4+length:]
    packed = zlib.compress(changed, 6)
    return (prefix + struct.pack("<I", len(packed)) + packed).hex().upper()


def sampler_tracks(root):
    result = {}
    for track in root.find("list[@name='track']"):
        if track.get("class") != "MSamplerTrackEvent":
            continue
        name = track.find("obj[@name='Node']/string[@name='Name']").get("value")
        if name in result:
            raise ValueError("Duplicate sampler track: " + name)
        result[name] = track
    return result


def component(track):
    found = []
    for node in track.iter("bin"):
        if node.get("name") != "audioComponent":
            continue
        try:
            unpack_component(node.text)
        except (ValueError, zlib.error):
            continue
        found.append(node)
    if len(found) != 1:
        raise ValueError("Expected exactly one Sampler Track instrument per track")
    return found[0]


def prepare_archive(template, slots, destination):
    root = ET.parse(template).getroot()
    tracks = sampler_tracks(root)
    wanted = {s["cubase"]["track_name"] for s in slots}
    if set(tracks) != wanted:
        raise ValueError("Track archive must have exactly the same numbered sampler tracks as the plan")
    track_list = root.find("list[@name='track']")
    for track in list(track_list):
        if track not in tracks.values():
            track_list.remove(track)
    for slot in slots:
        track = tracks[slot["cubase"]["track_name"]]
        path = Path(slot["cubase"]["sample_path"]).resolve()
        if not path.is_file():
            raise FileNotFoundError(path)
        node = component(track)
        node.text = replace_component_path(node.text, path)
        track.find("string[@name='SamplePath']").set("value", str(path))
    dest = Path(destination)
    ET.ElementTree(root).write(dest, encoding="utf-8", xml_declaration=True)
    return dest


def _signature(node):
    # Object identities can be regenerated by Cubase during export.
    if node.get("class") in {"MTempoTrackEvent", "MSignatureTrackEvent"}:
        # Exporting only sampler tracks embeds these shared timing objects;
        # exporting the complete project puts them at root without an alias.
        node = copy.deepcopy(node)
        node.attrib.pop("name", None)
    if node.get("class") == "MMidiNote":
        node = copy.deepcopy(node)
        velocity = node.find("float[@name='HrData']")
        attrs = node.find("member[@name='Additional Attributes']")
        if velocity is not None and attrs is not None:
            duplicate = attrs.find("float[@name='HRDT']")
            # Cubase Save As removes this redundant velocity mirror.
            if duplicate is not None and duplicate.get("value") == velocity.get("value"):
                attrs.remove(duplicate)
                if not len(attrs):
                    node.remove(attrs)
    return (node.tag, tuple(sorted((k, v) for k, v in node.attrib.items() if k != "ID")),
            (node.text or "").strip(), tuple(_signature(c) for c in node))


def verify_import(before, after, slots):
    before_root, after_root = ET.parse(before).getroot(), ET.parse(after).getroot()
    old, new = sampler_tracks(before_root), sampler_tracks(after_root)
    timing_classes = {"MTempoTrackEvent", "MSignatureTrackEvent"}
    if ([_signature(n) for n in before_root.iter("obj") if n.get("class") in timing_classes] !=
            [_signature(n) for n in after_root.iter("obj") if n.get("class") in timing_classes]):
        raise ValueError("Cubase tempo or time signature changed")
    expected = {s["cubase"]["track_name"]: str(Path(s["cubase"]["sample_path"]).resolve()) for s in slots}
    if set(old) != set(new) or set(new) != set(expected):
        raise ValueError("Sampler track inventory changed during import")
    if list(old) != list(new):
        raise ValueError("Sampler track order changed during import")
    for name, track in new.items():
        before_track = old[name]
        for field in ("Start", "Length"):
            a = before_track.find(f"float[@name='{field}']")
            b = track.find(f"float[@name='{field}']")
            if (None if a is None else _signature(a)) != (None if b is None else _signature(b)):
                raise ValueError("Track timing changed: " + name)
        old_automation = [_signature(n) for n in before_track.iter("obj") if n.get("class") == "MAutomationNode"]
        new_automation = [_signature(n) for n in track.iter("obj") if n.get("class") == "MAutomationNode"]
        if old_automation != new_automation:
            raise ValueError("Automation changed: " + name)
        old_notes = [_signature(n) for n in before_track.iter("obj") if n.get("class") in {"MMidiPartEvent", "MMidiNote"}]
        new_notes = [_signature(n) for n in track.iter("obj") if n.get("class") in {"MMidiPartEvent", "MMidiNote"}]
        if old_notes != new_notes:
            raise ValueError("MIDI changed: " + name)
        old_comp, new_comp = component(before_track), component(track)
        _, body = unpack_component(new_comp.text)
        if sample_field(body)[2].casefold() != expected[name].casefold():
            raise ValueError("Cubase did not load the selected sample: " + name)
        _, expected_body = unpack_component(replace_component_path(old_comp.text, expected[name]))
        if body != expected_body:
            raise ValueError("Sampler parameters changed beyond its filename: " + name)
        old_fx = ["".join((n.text or "").split()) for n in before_track.iter("bin")
                  if n is not old_comp and n.get("name") != "editController"]
        new_fx = ["".join((n.text or "").split()) for n in track.iter("bin")
                  if n is not new_comp and n.get("name") != "editController"]
        if old_fx != new_fx:
            raise ValueError("Effect state changed: " + name)
        # Routing, gain, pan and channel configuration are outside the compressed
        # instrument state. Ignore only the sampler payload already checked above
        # and its transient UI controller cache.
        def channel_signature(source):
            device = copy.deepcopy(source.find("obj[@name='Track Device']"))
            if device is None:
                return None
            component(device).text = ""
            for parent in device.iter():
                for child in list(parent):
                    if child.tag == "bin" and child.get("name") == "editController":
                        parent.remove(child)
            return _signature(device)
        if channel_signature(before_track) != channel_signature(track):
            raise ValueError("Channel configuration or routing changed: " + name)
    return {"verified_tracks": len(expected), "midi_preserved": True,
            "sampler_parameters_preserved": True, "effects_preserved": True, "tempo_preserved": True,
            "track_order_preserved": True, "track_timing_preserved": True,
            "automation_preserved": True, "channel_configuration_preserved": True}


def template_for_project(project, template_dir=None):
    directory = Path(template_dir or Path(__file__).resolve().parents[3] / "templates" / "cubase")
    digest = hashlib.sha256(Path(project).read_bytes()).hexdigest()
    for meta in directory.glob("*.json"):
        info = json.loads(meta.read_text(encoding="utf-8"))
        archive = meta.with_suffix(".xml")
        if info.get("project_sha256") == digest and archive.is_file():
            return archive
    return None
